# Generated by Django 5.2.7 on 2025-10-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0002_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
