# Generated by Django 5.2.7 on 2025-10-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
