# Generated by Django 5.2.7 on 2025-10-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0004_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
