# Generated by Django 5.2.7 on 2025-10-04 15:24

import books_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0005_alter_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to=books_management.models.books_img_directory_name),
        ),
    ]
