# Generated by Django 5.2.7 on 2025-10-04 16:27

import books_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=books_management.models.books_img_directory_name),
        ),
    ]
